{{- if .Values.armAuth -}}
{{- if .Values.armAuth.secretName -}}
{{- if eq .Values.armAuth.type "servicePrincipal" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.armAuth.secretName }}
type: Opaque
data:
  armAuth.json: "{{- required "armAuth.secretJSON is required when using servicePrincipal" .Values.armAuth.secretJSON -}}"
{{- end -}}
{{- end -}}
{{- end -}}